from enum import Enum

class ProjectState(str, Enum):
    INIT = "INIT"
    DISCOVERY = "DISCOVERY"
    SPEC = "SPEC"
    WORK_PACKAGE = "WORK_PACKAGE"
    SPRINT_PLANNING = "SPRINT_PLANNING"
    DEVELOPMENT = "DEVELOPMENT"
    TEST = "TEST"
    BLOCKED = "BLOCKED"
    SPRINT_REVIEW = "SPRINT_REVIEW"
    PR_CREATED = "PR_CREATED"
    RETROSPECTIVE = "RETROSPECTIVE"
    DONE = "DONE"
