from pathlib import Path
from typing import Dict, Any
from sdk.base_agent import BaseAgentSDK
from kernel.event_bus.events import Event, EventType
from contracts.work_package import WorkPackage

class DeveloperAgent(BaseAgentSDK):
    def register_subscriptions(self) -> None:
        self.bus.subscribe(EventType.SPRINT_PLANNING_APPROVED, self.process_event)
        self.bus.subscribe(EventType.TESTS_FAILED, self.handle_retry)

    async def process_event(self, event: Event) -> None:
        payload = event.payload
        wp_dict = payload.get("work_package", {})
        project_root = Path(payload.get("project_root", "."))
        wp = WorkPackage.model_validate(wp_dict)

        self.logger.info(f"DeveloperAgent starting development for {wp.id}")
        written_files = self._generate_code_and_tests(project_root, wp)

        await self.emit_event(
            event_type=EventType.DEVELOPMENT_COMPLETED,
            payload={
                "work_package": wp.model_dump(),
                "written_files": written_files,
                "project_root": str(project_root)
            },
            correlation_id=event.correlation_id
        )

    async def handle_retry(self, event: Event) -> None:
        payload = event.payload
        retry_count = payload.get("retry_count", 0)
        max_retries = payload.get("max_retries", 3)
        if retry_count >= max_retries:
            self.logger.warning(f"Max retries ({max_retries}) reached. Escalating to PIPELINE_BLOCKED.")
            await self.emit_event(
                event_type=EventType.PIPELINE_BLOCKED,
                payload={
                    "reason": f"Max retries ({max_retries}) reached without passing tests. Last error: {payload.get('error', '')}",
                    "sprint_id": payload.get("work_package", {}).get("sprint_id", "UNKNOWN"),
                    "work_package_id": payload.get("work_package", {}).get("id", "UNKNOWN")
                },
                correlation_id=event.correlation_id
            )
            return

        self.logger.info(f"DeveloperAgent retrying development (retry {retry_count + 1}/{max_retries})")
        wp_dict = payload.get("work_package", {})
        project_root = Path(payload.get("project_root", "."))
        wp = WorkPackage.model_validate(wp_dict)

        written_files = self._generate_code_and_tests(project_root, wp, is_retry=True)

        await self.emit_event(
            event_type=EventType.DEVELOPMENT_COMPLETED,
            payload={
                "work_package": wp.model_dump(),
                "written_files": written_files,
                "project_root": str(project_root),
                "retry_count": retry_count + 1
            },
            correlation_id=event.correlation_id
        )

    def _generate_code_and_tests(self, project_root: Path, wp: WorkPackage, is_retry: bool = False) -> Dict[str, str]:
        src_dir = project_root / "src"
        tests_dir = project_root / "tests"
        src_dir.mkdir(parents=True, exist_ok=True)
        tests_dir.mkdir(parents=True, exist_ok=True)

        written = {}

        # Create __init__.py files
        (src_dir / "__init__.py").touch()
        (tests_dir / "__init__.py").touch()

        # Generate module file for tasks
        module_file = src_dir / "app.py"
        module_code = '"""Application module generated by AI-SD-OS DeveloperAgent."""\n\n'

        test_file = tests_dir / "test_app.py"
        test_code = "import sys, os\nsys.path.insert(0, os.path.abspath('.'))\nimport pytest\nfrom src.app import *\n\n"

        for task in wp.tasks:
            req_id = task.requirement_ref
            fn_name = req_id.lower().replace("-", "_") + "_feature"
            module_code += f"def {fn_name}():\n    return '{req_id} OK'\n\n"

            test_names = wp.coverage_mapping.get(req_id, [f"test_{fn_name}"])
            for tname in test_names:
                test_code += f"def {tname}():\n    assert {fn_name}() == '{req_id} OK'\n\n"

        with open(module_file, "w", encoding="utf-8") as f:
            f.write(module_code)
        written[str(module_file)] = module_code

        with open(test_file, "w", encoding="utf-8") as f:
            f.write(test_code)
        written[str(test_file)] = test_code

        return written
